networks:
  dev:
    driver: bridge

volumes:
  db-data: { }
  redis-data: { }
  minio-data: { }

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=${DB_USER};Password=${DB_PASSWORD};Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - JWT__KEY=${ASPNETCORE_JWT_KEY}
      - JWT__ISSUER=${ASPNETCORE_JWT_ISSUER}
      - JWT__AUDIENCE=${ASPNETCORE_JWT_AUDIENCE}
    ports:
      - "${ASPNETCORE_PORT:-8080}:8080"
    networks:
      - dev 
    depends_on:
      - postgres
    
  postgres:
    image: postgres:18-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}",
        ]
      interval: 10s
      retries: 15
      start_period: 10s
      timeout: 5s
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - dev
    restart: unless-stopped